/* SPDX-License-Identifier: GPL-2.0 */
/* HTTPS-Guard eBPF program – OpenSSL SSL_write/SSL_read uprobes (PRIMARY detection)
 *
 * Hooks both directions of OpenSSL plaintext I/O:
 *   - SSL_write(SSL *ssl, const void *buf, int num) — data the process sends
 *   - SSL_read(SSL *ssl, void *buf, int num)        — data the process receives
 * to:
 *   1. Read the negotiated TLS version from the SSL struct (ssl->version).
 *   2. Capture plaintext HTTP payloads for anomaly detection.
 *
 * This is the PRIMARY enforcement path for BMCs because XDP is not
 * available on ASpeed AST2600 ftgmac100 NICs (the typical BMC
 * network controller).  The uprobe works on all platforms since it
 * only requires userspace uprobe support (CONFIG_UPROBES).
 *
 * WHY SSL_read NEEDS TWO PROBES, NOT ONE:
 * ----------------------------------------
 * SSL_write's buf already holds the plaintext to send when the call is
 * entered, so a single entry-only uprobe can read it directly. SSL_read's
 * buf is the opposite: it's an output parameter OpenSSL fills DURING the
 * call, so at entry it's uninitialized — reading it there would capture
 * garbage, not the received request. The fix is a paired entry+return
 * uprobe: the entry probe stashes the ssl/buf pointers (keyed by
 * pid_tgid, since register state at return no longer holds the original
 * arguments), and the return probe retrieves them, reads the actual
 * bytes-read count from the return value, and only then reads buf.
 *
 * DESIGN PRINCIPLE: BPF is PURELY OBSERVATIONAL.
 * -------------------------------------------------
 * This uprobe does NOT classify events or make security decisions.
 * It only reads raw data from the process and forwards it to the
 * ring buffer.  All classification (TLS version violation vs normal
 * traffic, anomaly detection) happens in userspace, where we have
 * access to the full C++ standard library.
 *
 * DATA READ FROM THE PROCESS:
 *   - ssl->version:  The negotiated TLS version code, read from
 *     the OpenSSL ssl_st struct at the build-time determined offset
 *     (SSL_VERSION_OFFSET, generated by scripts/gen_ssl_offset.c
 *     using offsetof(struct ssl_st, version) from the actual headers).
 *   - buf[0..num]:   A snippet of the plaintext payload sent (SSL_write)
 *     or received (SSL_read).
 *   - pid/tgid:      Process identification for socket correlation.
 *
 * MEMORY ACCESS:
 *   All data pointers (ssl, buf) are userspace virtual addresses in
 *   the probed process.  We use bpf_probe_read_user() which safely
 *   handles page faults — if a pointer is invalid, it returns -EFAULT
 *   and the output buffer remains zeroed.
 *
 * CO-RE NOTE:
 *   We do NOT use bpf_core_read() (or BPF_CORE_READ()) for ssl_st because
 *   CO-RE relocations
 *   require the target type to exist in the kernel's BTF — but ssl_st is a
 *   userspace struct from libssl.so, not a kernel struct.  The kernel BTF
 *   has no type ID for it, so any CO-RE relocation for ssl_st fields will
 *   fail at program load time with "invalid CO-RE relocation".  Instead we
 *   read ssl->version directly from userspace memory using
 *   bpf_probe_read_user() with the build-time offset from gen_ssl_offset.c.
 *   ssl_st is a userspace type and is intentionally not declared in
 *   vmlinux.h; the event structs in ssl_uprobe_event.h are this project's
 *   BPF-to-userspace wire structs, not kernel BTF structs.
 */
#pragma once

#include "ssl_uprobe_event.h"

/* Build-time generated header with the offset of ssl_st.version.
 * Produced by scripts/gen_ssl_offset.c, which uses hardcoded
 * architecture-specific offsets (OpenSSL 3.x made ssl_st opaque). */
#include "ssl_version_offset.h"

static __always_inline int
fill_uprobe_event_fields(struct uprobe_event *evt, enum hg_uprobe_direction direction)
{
    evt->hdr.event_source = HG_SOURCE_UPROBE;
    evt->direction = direction;

    __u64 pid_tgid = bpf_get_current_pid_tgid();
    evt->hdr.pid = (__u32)pid_tgid;
    evt->hdr.tgid = (__u32)(pid_tgid >> 32);
    evt->hdr.timestamp_ns = bpf_ktime_get_ns();
    bpf_get_current_comm(&evt->hdr.comm, sizeof(evt->hdr.comm));
    evt->hdr.reserved = 0;
    evt->padding      = 0;
    return 0;
}

/* ---------------------------------------------------------------
 * Read ssl->version from userspace memory at the build-time
 * determined offset.  The negotiated TLS version (e.g. TLS 1.2 =
 * 0x0303, TLS 1.3 = 0x0304) is stored in the lower 16 bits of this
 * 4-byte int. Shared by both SSL_write and SSL_read, since the
 * offset and meaning are identical either way.
 * --------------------------------------------------------------- */
static __always_inline __u16
read_tls_version(const void *ssl)
{
    __u32 version_raw = 0;

    if (bpf_probe_read_user(&version_raw, sizeof(version_raw),
                            (const void *)((uintptr_t)ssl + SSL_VERSION_OFFSET)) == 0)
    {
        return (__u16)(version_raw & 0xFFFF);
    }
    return 0;
}

/*
 * SSL_write(SSL *ssl, const void *buf, int num)
 *   - arg1: ssl  (pointer to SSL object – read version from here)
 *   - arg2: buf  (pointer to plaintext already being sent — valid at entry)
 *   - arg3: num  (length in bytes)
 */
/* =========================================================================
 * Kernel-side session binding.
 *
 * Resolves an SSL_write/SSL_read event's own connection tuple entirely in
 * BPF, without /proc: a kprobe on tcp_recvmsg/tcp_sendmsg records the port-
 * 443 socket a thread most recently touched; SSL_accept/SSL_connect
 * consumes that record (exactly once) to bind the calling SSL session to
 * it; SSL_write/SSL_read then look the session up by its own ssl pointer
 * and embed the tuple directly into the event they already submit.
 * SSL_free clears the binding. See LIMITATIONS.md for the thread-affinity
 * assumption this relies on and why it is safe to ship unverified: the
 * single-use per-thread key means a wrong assumption only ever under-binds
 * (falls back to /proc), never mis-binds.
 *
 * LRU_HASH, not HASH, for both maps -- the same reasoning xdp_tls's
 * per-source counter map already uses: bounded by construction, and a
 * thread or session whose binding is never consumed/freed (a non-TLS
 * process touching port 443, a session freed by a path this hook doesn't
 * observe) ages out under turnover instead of leaking forever.
 * ========================================================================= */

#define HG_SESSION_TUPLE_PORT 443
/* Stable Linux UAPI values (include/linux/socket.h), never change across
 * architectures or kernel versions -- not sourced from vmlinux.h because
 * these are #defines, not BTF-visible types. */
#define HG_AF_INET  2
#define HG_AF_INET6 10

struct hg_bound_tuple {
    __u8  is_ipv6;
    __u8  padding[7];
    __u8  local_addr[16];
    __u8  remote_addr[16];
    __u16 local_port;   /* host byte order */
    __u16 remote_port;  /* host byte order */
    __u64 timestamp_ns;
};

/* {pid_tgid -> the port-443 socket this thread most recently touched}. */
struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 1024);
    __type(key, __u64);
    __type(value, struct hg_bound_tuple);
} https_guard_thread_tuple_map SEC(".maps");

/* {SSL* (as an integer) -> its bound tuple}. */
struct {
    __uint(type, BPF_MAP_TYPE_LRU_HASH);
    __uint(max_entries, 1024);
    __type(key, __u64);
    __type(value, struct hg_bound_tuple);
} https_guard_session_tuple_map SEC(".maps");

/*
 * Populates *out from a kernel struct sock*, iff local or remote port is
 * 443. sk is untrusted/untyped as far as the verifier is concerned -- it
 * comes from a classic kprobe's pt_regs, not a BTF-typed fentry/LSM
 * argument -- so every field is read via BPF_CORE_READ_INTO(), the same
 * "don't dereference directly, read explicitly" rule this file already
 * applies to ssl (bpf_probe_read_user()), just for kernel memory instead of
 * userspace memory, and with CO-RE relocation since struct sock (unlike
 * ssl_st) actually has kernel BTF to relocate against.
 *
 * skc_num (local port) is host byte order; skc_dport (remote port) is
 * network byte order -- a real, well-known kernel inconsistency, not a
 * copy-paste mismatch between the two reads below.
 */
static __always_inline int
read_sock_tuple_if_port_443(struct sock *sk, struct hg_bound_tuple *out)
{
    __u16 family = 0, num_host = 0, dport_be = 0;

    /* sk_family/sk_num/sk_dport/sk_daddr/... are #define aliases for
     * __sk_common.skc_* in the kernel's own include/net/sock.h -- real
     * macros, not BTF-visible members, so vmlinux.h (a BTF dump: types
     * only, no preprocessor) does not have them. The first build of this
     * code assumed otherwise and failed with "no member named 'sk_family'
     * in 'struct sock'"; the real, relocatable path is __sk_common.skc_*. */
    BPF_CORE_READ_INTO(&family, sk, __sk_common.skc_family);
    BPF_CORE_READ_INTO(&num_host, sk, __sk_common.skc_num);
    BPF_CORE_READ_INTO(&dport_be, sk, __sk_common.skc_dport);
    __u16 dport_host = bpf_ntohs(dport_be);

    if (num_host != HG_SESSION_TUPLE_PORT && dport_host != HG_SESSION_TUPLE_PORT)
    {
        return 0;
    }

    __builtin_memset(out, 0, sizeof(*out));
    out->local_port   = num_host;
    out->remote_port  = dport_host;
    out->timestamp_ns = bpf_ktime_get_ns();

    /* A dual-stack listener (bmcweb binds "::") reports skc_family == AF_INET6
     * for an IPv4 peer same as for a real IPv6 one -- but only sets the
     * legacy skc_rcv_saddr/skc_daddr for the IPv4-mapped case; the
     * skc_v6_rcv_saddr/skc_v6_daddr fields (checked first, so a real IPv6
     * peer still takes that branch) are left all-zero rather than holding an
     * an actual ::ffff:a.b.c.d form. So a nonzero legacy field is the signal
     * that this AF_INET6 socket's peer is really IPv4 -- checked before
     * trusting family alone, which is what made every dual-stack-accepted
     * IPv4 peer resolve to an all-zero address (verified live: bmcweb's own
     * connections never attributed, while a plain AF_INET-socket client's
     * did). */
    __u32 legacy_saddr = 0, legacy_daddr = 0;
    BPF_CORE_READ_INTO(&legacy_saddr, sk, __sk_common.skc_rcv_saddr);
    BPF_CORE_READ_INTO(&legacy_daddr, sk, __sk_common.skc_daddr);

    if (family == HG_AF_INET6 && legacy_daddr == 0)
    {
        out->is_ipv6 = 1;
        BPF_CORE_READ_INTO(out->local_addr, sk, __sk_common.skc_v6_rcv_saddr);
        BPF_CORE_READ_INTO(out->remote_addr, sk, __sk_common.skc_v6_daddr);
    }
    else
    {
        __builtin_memcpy(out->local_addr, &legacy_saddr, sizeof(legacy_saddr));
        __builtin_memcpy(out->remote_addr, &legacy_daddr, sizeof(legacy_daddr));
    }

    return 1;
}

/* tcp_recvmsg(struct sock *sk, struct msghdr *msg, size_t len, int flags)
 * tcp_sendmsg(struct sock *sk, struct msghdr *msg, size_t size)
 * Both take sk as arg1 -- verified against this project's own target kernel
 * source (net/ipv4/tcp.c, v6.18), not assumed, since this signature is not
 * part of any stable kernel ABI and has changed across versions before. */
SEC("kprobe/tcp_recvmsg")
int https_guard_tcp_recvmsg(struct pt_regs *ctx)
{
    struct sock *sk = (struct sock *)PT_REGS_PARM1(ctx);
    struct hg_bound_tuple tup;

    if (!sk || !read_sock_tuple_if_port_443(sk, &tup))
    {
        return 0;
    }

    __u64 pid_tgid = bpf_get_current_pid_tgid();
    bpf_map_update_elem(&https_guard_thread_tuple_map, &pid_tgid, &tup, BPF_ANY);
    return 0;
}

SEC("kprobe/tcp_sendmsg")
int https_guard_tcp_sendmsg(struct pt_regs *ctx)
{
    struct sock *sk = (struct sock *)PT_REGS_PARM1(ctx);
    struct hg_bound_tuple tup;

    if (!sk || !read_sock_tuple_if_port_443(sk, &tup))
    {
        return 0;
    }

    __u64 pid_tgid = bpf_get_current_pid_tgid();
    bpf_map_update_elem(&https_guard_thread_tuple_map, &pid_tgid, &tup, BPF_ANY);
    return 0;
}

/*
 * Binds `ssl` to the calling thread's most recently recorded port-443
 * tuple, consuming it (read then delete) so it cannot be reused by a later,
 * unrelated handshake on the same thread -- the safety property that keeps
 * a wrong thread-affinity assumption from ever mis-binding, only
 * under-binding. Does nothing if this thread has no such record: the
 * event(s) for this session simply fall back to /proc, exactly as if this
 * mechanism did not exist.
 */
static __always_inline void bind_session_from_thread(const void *ssl)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    struct hg_bound_tuple *tup =
        bpf_map_lookup_elem(&https_guard_thread_tuple_map, &pid_tgid);
    if (!tup)
    {
        return;
    }

    __u64 ssl_key = (__u64)(uintptr_t)ssl;
    bpf_map_update_elem(&https_guard_session_tuple_map, &ssl_key, tup, BPF_ANY);
    bpf_map_delete_elem(&https_guard_thread_tuple_map, &pid_tgid);
}

/* SSL_accept(SSL *ssl) -- a connection this box accepted (bmcweb's normal
 * case). SSL_connect(SSL *ssl) -- one this box initiated (e.g. a local
 * openssl s_client). Either way arg1 is the SSL*. */
SEC("uprobe/ssl_accept")
int https_guard_ssl_accept(struct pt_regs *ctx)
{
    const void *ssl = (const void *)PT_REGS_PARM1(ctx);
    if (ssl)
    {
        bind_session_from_thread(ssl);
    }
    return 0;
}

SEC("uprobe/ssl_connect")
int https_guard_ssl_connect(struct pt_regs *ctx)
{
    const void *ssl = (const void *)PT_REGS_PARM1(ctx);
    if (ssl)
    {
        bind_session_from_thread(ssl);
    }
    return 0;
}

/* SSL_free(SSL *ssl) -- releases this session's binding promptly, rather
 * than waiting for LRU eviction under turnover. */
SEC("uprobe/ssl_free")
int https_guard_ssl_free(struct pt_regs *ctx)
{
    const void *ssl = (const void *)PT_REGS_PARM1(ctx);
    if (ssl)
    {
        __u64 ssl_key = (__u64)(uintptr_t)ssl;
        bpf_map_delete_elem(&https_guard_session_tuple_map, &ssl_key);
    }
    return 0;
}

/* Looks `ssl` up in the session map and, on a hit, fills *out (resolved=1).
 * On a miss *out is left however the caller already zeroed it (resolved=0)
 * -- called right after __builtin_memset(evt, 0, sizeof(*evt)) in both
 * SSL_write and SSL_read's handlers below. */
static __always_inline void
fill_resolved_conn(const void *ssl, struct hg_uprobe_conn *out)
{
    __u64 ssl_key = (__u64)(uintptr_t)ssl;
    struct hg_bound_tuple *tup =
        bpf_map_lookup_elem(&https_guard_session_tuple_map, &ssl_key);
    if (!tup)
    {
        return;
    }

    out->resolved     = 1;
    out->is_ipv6      = tup->is_ipv6;
    out->local_port   = tup->local_port;
    out->remote_port  = tup->remote_port;
    __builtin_memcpy(out->local_addr, tup->local_addr, sizeof(out->local_addr));
    __builtin_memcpy(out->remote_addr, tup->remote_addr, sizeof(out->remote_addr));
}

SEC("uprobe/ssl_write")
int https_guard_ssl_write(struct pt_regs *ctx)
{
    const void *ssl = (const void *)PT_REGS_PARM1(ctx);
    const void *buf = (const void *)PT_REGS_PARM2(ctx);
    int num = (int)PT_REGS_PARM3(ctx);

    if (num <= 0 || !buf || !ssl)
    {
        return 0;
    }

    // Would output to /sys/kernel/debug/tracing/trace_pipe
    bpf_printk("https_guard: SSL_write hit pid=%d num=%d\n",
               bpf_get_current_pid_tgid() >> 32, num);

    struct uprobe_event *evt;

    evt = bpf_ringbuf_reserve(&events, sizeof(*evt), 0);
    if (!evt)
    {
        return 0;
    }

    __builtin_memset(evt, 0, sizeof(*evt));
    fill_uprobe_event_fields(evt, HG_UPROBE_DIR_WRITE);

    /* PURELY OBSERVATIONAL - no classification, no event_type, no severity.
     * Just capture raw data and let userspace decide what it means. */
    evt->tls.version = read_tls_version(ssl);
    fill_resolved_conn(ssl, &evt->resolved_conn);

    /* Capture a snippet of the plaintext payload for anomaly detection */
    int copy_sz = num < (int)sizeof(evt->tls.payload_snippet) - 1
                      ? num
                      : (int)sizeof(evt->tls.payload_snippet) - 1;

    bpf_probe_read_user(evt->tls.payload_snippet, copy_sz, buf);
    evt->tls.payload_snippet[copy_sz] = '\0';

    bpf_ringbuf_submit(evt, 0);
    return 0;
}

/* =========================================================================
 * SSL_read(SSL *ssl, void *buf, int num) — the request-side mirror.
 *
 * buf is an OUTPUT parameter here: OpenSSL fills it DURING the call, so
 * it's uninitialized at entry. A paired entry+return uprobe captures it
 * correctly instead:
 *   1. https_guard_ssl_read_entry (entry, not a retprobe): stash ssl/buf
 *      pointers, keyed by pid_tgid, into a scratch map. Register state
 *      at return no longer holds the original call's arguments, so this
 *      is the only point they're available.
 *   2. https_guard_ssl_read_exit (retprobe): retrieve the stashed
 *      pointers, read the actual bytes-read count from the return value
 *      (NOT the original num — that's only the buffer's capacity, and
 *      using it instead of the real count would copy trailing
 *      uninitialized/stale bytes as if they were received data), then
 *      read ssl->version and buf exactly as SSL_write's hook does.
 * ========================================================================= */

struct https_guard_ssl_read_args {
    __u64 ssl;
    __u64 buf;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 1024);
    __type(key, __u64);    /* pid_tgid */
    __type(value, struct https_guard_ssl_read_args);
} https_guard_ssl_read_args_map SEC(".maps");

SEC("uprobe/ssl_read")
int https_guard_ssl_read_entry(struct pt_regs *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    struct https_guard_ssl_read_args args = {
        .ssl = (__u64)PT_REGS_PARM1(ctx),
        .buf = (__u64)PT_REGS_PARM2(ctx),
    };

    if (!args.ssl || !args.buf)
    {
        return 0;
    }

    bpf_map_update_elem(&https_guard_ssl_read_args_map, &pid_tgid, &args, BPF_ANY);
    return 0;
}

SEC("uprobe/ssl_read")
int https_guard_ssl_read_exit(struct pt_regs *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    struct https_guard_ssl_read_args *args =
        bpf_map_lookup_elem(&https_guard_ssl_read_args_map, &pid_tgid);

    if (!args)
    {
        return 0;
    }

    /* SSL_read's return value is the number of bytes actually read, or
     * <= 0 on error/no data — nothing genuinely arrived in that case. */
    int num_read = (int)PT_REGS_RC(ctx);
    __u64 ssl = args->ssl;
    __u64 buf = args->buf;

    bpf_map_delete_elem(&https_guard_ssl_read_args_map, &pid_tgid);

    if (num_read <= 0)
    {
        return 0;
    }

    bpf_printk("https_guard: SSL_read hit pid=%d num_read=%d\n",
               pid_tgid >> 32, num_read);

    struct uprobe_event *evt;

    evt = bpf_ringbuf_reserve(&events, sizeof(*evt), 0);
    if (!evt)
    {
        return 0;
    }

    __builtin_memset(evt, 0, sizeof(*evt));
    fill_uprobe_event_fields(evt, HG_UPROBE_DIR_READ);

    evt->tls.version = read_tls_version((const void *)ssl);
    fill_resolved_conn((const void *)ssl, &evt->resolved_conn);

    int copy_sz = num_read < (int)sizeof(evt->tls.payload_snippet) - 1
                      ? num_read
                      : (int)sizeof(evt->tls.payload_snippet) - 1;

    bpf_probe_read_user(evt->tls.payload_snippet, copy_sz, (const void *)buf);
    evt->tls.payload_snippet[copy_sz] = '\0';

    bpf_ringbuf_submit(evt, 0);
    return 0;
}
