/* SPDX-License-Identifier: GPL-2.0 */
/* HTTPS-Guard eBPF program – OpenSSL SSL_write/SSL_read uprobes (PRIMARY detection)
 *
 * Hooks both directions of OpenSSL plaintext I/O:
 *   - SSL_write(SSL *ssl, const void *buf, int num) — data the process sends
 *   - SSL_read(SSL *ssl, void *buf, int num)        — data the process receives
 * to:
 *   1. Read the negotiated TLS version from the SSL struct (ssl->version).
 *   2. Capture plaintext HTTP payloads for anomaly detection.
 *
 * This is the PRIMARY enforcement path for BMCs because XDP is not
 * available on ASpeed AST2600 ftgmac100 NICs (the typical BMC
 * network controller).  The uprobe works on all platforms since it
 * only requires userspace uprobe support (CONFIG_UPROBES).
 *
 * WHY SSL_read NEEDS TWO PROBES, NOT ONE:
 * ----------------------------------------
 * SSL_write's buf already holds the plaintext to send when the call is
 * entered, so a single entry-only uprobe can read it directly. SSL_read's
 * buf is the opposite: it's an output parameter OpenSSL fills DURING the
 * call, so at entry it's uninitialized — reading it there would capture
 * garbage, not the received request. The fix is a paired entry+return
 * uprobe: the entry probe stashes the ssl/buf pointers (keyed by
 * pid_tgid, since register state at return no longer holds the original
 * arguments), and the return probe retrieves them, reads the actual
 * bytes-read count from the return value, and only then reads buf.
 *
 * DESIGN PRINCIPLE: BPF is PURELY OBSERVATIONAL.
 * -------------------------------------------------
 * This uprobe does NOT classify events or make security decisions.
 * It only reads raw data from the process and forwards it to the
 * ring buffer.  All classification (TLS version violation vs normal
 * traffic, anomaly detection) happens in userspace, where we have
 * access to the full C++ standard library.
 *
 * DATA READ FROM THE PROCESS:
 *   - ssl->version:  The negotiated TLS version code, read from
 *     the OpenSSL ssl_st struct at the build-time determined offset
 *     (SSL_VERSION_OFFSET, generated by scripts/gen_ssl_offset.c
 *     using offsetof(struct ssl_st, version) from the actual headers).
 *   - buf[0..num]:   A snippet of the plaintext payload sent (SSL_write)
 *     or received (SSL_read).
 *   - pid/tgid:      Process identification for socket correlation.
 *
 * MEMORY ACCESS:
 *   All data pointers (ssl, buf) are userspace virtual addresses in
 *   the probed process.  We use bpf_probe_read_user() which safely
 *   handles page faults — if a pointer is invalid, it returns -EFAULT
 *   and the output buffer remains zeroed.
 *
 * CO-RE NOTE:
 *   We do NOT use bpf_core_read() for ssl_st because CO-RE relocations
 *   require the target type to exist in the kernel's BTF — but ssl_st is a
 *   userspace struct from libssl.so, not a kernel struct.  The kernel BTF
 *   has no type ID for it, so any CO-RE relocation for ssl_st fields will
 *   fail at program load time with "invalid CO-RE relocation".  Instead we
 *   read ssl->version directly from userspace memory using
 *   bpf_probe_read_user() with the build-time offset from gen_ssl_offset.c.
 */
#pragma once

#include "ssl_uprobe_event.h"

/* Build-time generated header with the offset of ssl_st.version.
 * Produced by scripts/gen_ssl_offset.c, which uses hardcoded
 * architecture-specific offsets (OpenSSL 3.x made ssl_st opaque). */
#include "ssl_version_offset.h"

static __always_inline int
fill_uprobe_event_fields(struct uprobe_event *evt, enum hg_uprobe_direction direction)
{
    evt->hdr.event_source = HG_SOURCE_UPROBE;
    evt->direction = direction;

    __u64 pid_tgid = bpf_get_current_pid_tgid();
    evt->hdr.pid = (__u32)pid_tgid;
    evt->hdr.tgid = (__u32)(pid_tgid >> 32);
    evt->hdr.timestamp_ns = bpf_ktime_get_ns();
    bpf_get_current_comm(&evt->hdr.comm, sizeof(evt->hdr.comm));
    evt->hdr.reserved = 0;
    evt->padding      = 0;
    return 0;
}

/* ---------------------------------------------------------------
 * Read ssl->version from userspace memory at the build-time
 * determined offset.  The negotiated TLS version (e.g. TLS 1.2 =
 * 0x0303, TLS 1.3 = 0x0304) is stored in the lower 16 bits of this
 * 4-byte int. Shared by both SSL_write and SSL_read, since the
 * offset and meaning are identical either way.
 * --------------------------------------------------------------- */
static __always_inline __u16
read_tls_version(const void *ssl)
{
    __u32 version_raw = 0;

    if (bpf_probe_read_user(&version_raw, sizeof(version_raw),
                            (const void *)((uintptr_t)ssl + SSL_VERSION_OFFSET)) == 0) {
        return (__u16)(version_raw & 0xFFFF);
    }
    return 0;
}

/*
 * SSL_write(SSL *ssl, const void *buf, int num)
 *   - arg1: ssl  (pointer to SSL object – read version from here)
 *   - arg2: buf  (pointer to plaintext already being sent — valid at entry)
 *   - arg3: num  (length in bytes)
 */
SEC("uprobe/ssl_write")
int https_guard_ssl_write(struct pt_regs *ctx)
{
    const void *ssl = (const void *)PT_REGS_PARM1(ctx);
    const void *buf = (const void *)PT_REGS_PARM2(ctx);
    int num = (int)PT_REGS_PARM3(ctx);

    if (num <= 0 || !buf || !ssl)
        return 0;

    // Would output to /sys/kernel/debug/tracing/trace_pipe
    bpf_printk("https_guard: SSL_write hit pid=%d num=%d\n",
               bpf_get_current_pid_tgid() >> 32, num);

    struct uprobe_event *evt;

    evt = bpf_ringbuf_reserve(&events, sizeof(*evt), 0);
    if (!evt)
        return 0;

    __builtin_memset(evt, 0, sizeof(*evt));
    fill_uprobe_event_fields(evt, HG_UPROBE_DIR_WRITE);

    /* PURELY OBSERVATIONAL - no classification, no event_type, no severity.
     * Just capture raw data and let userspace decide what it means. */
    evt->tls.version = read_tls_version(ssl);

    /* Capture a snippet of the plaintext payload for anomaly detection */
    int copy_sz = num < (int)sizeof(evt->tls.payload_snippet) - 1
                      ? num
                      : (int)sizeof(evt->tls.payload_snippet) - 1;

    bpf_probe_read_user(evt->tls.payload_snippet, copy_sz, buf);
    evt->tls.payload_snippet[copy_sz] = '\0';

    bpf_ringbuf_submit(evt, 0);
    return 0;
}

/* =========================================================================
 * SSL_read(SSL *ssl, void *buf, int num) — the request-side mirror.
 *
 * buf is an OUTPUT parameter here: OpenSSL fills it DURING the call, so
 * it's uninitialized at entry. A paired entry+return uprobe captures it
 * correctly instead:
 *   1. https_guard_ssl_read_entry (entry, not a retprobe): stash ssl/buf
 *      pointers, keyed by pid_tgid, into a scratch map. Register state
 *      at return no longer holds the original call's arguments, so this
 *      is the only point they're available.
 *   2. https_guard_ssl_read_exit (retprobe): retrieve the stashed
 *      pointers, read the actual bytes-read count from the return value
 *      (NOT the original num — that's only the buffer's capacity, and
 *      using it instead of the real count would copy trailing
 *      uninitialized/stale bytes as if they were received data), then
 *      read ssl->version and buf exactly as SSL_write's hook does.
 * ========================================================================= */

struct https_guard_ssl_read_args {
    __u64 ssl;
    __u64 buf;
};

struct {
    __uint(type, BPF_MAP_TYPE_HASH);
    __uint(max_entries, 1024);
    __type(key, __u64);    /* pid_tgid */
    __type(value, struct https_guard_ssl_read_args);
} https_guard_ssl_read_args_map SEC(".maps");

SEC("uprobe/ssl_read")
int https_guard_ssl_read_entry(struct pt_regs *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    struct https_guard_ssl_read_args args = {
        .ssl = (__u64)PT_REGS_PARM1(ctx),
        .buf = (__u64)PT_REGS_PARM2(ctx),
    };

    if (!args.ssl || !args.buf)
        return 0;

    bpf_map_update_elem(&https_guard_ssl_read_args_map, &pid_tgid, &args, BPF_ANY);
    return 0;
}

SEC("uprobe/ssl_read")
int https_guard_ssl_read_exit(struct pt_regs *ctx)
{
    __u64 pid_tgid = bpf_get_current_pid_tgid();
    struct https_guard_ssl_read_args *args =
        bpf_map_lookup_elem(&https_guard_ssl_read_args_map, &pid_tgid);

    if (!args)
        return 0;

    /* SSL_read's return value is the number of bytes actually read, or
     * <= 0 on error/no data — nothing genuinely arrived in that case. */
    int num_read = (int)PT_REGS_RC(ctx);
    __u64 ssl = args->ssl;
    __u64 buf = args->buf;

    bpf_map_delete_elem(&https_guard_ssl_read_args_map, &pid_tgid);

    if (num_read <= 0)
        return 0;

    bpf_printk("https_guard: SSL_read hit pid=%d num_read=%d\n",
               pid_tgid >> 32, num_read);

    struct uprobe_event *evt;

    evt = bpf_ringbuf_reserve(&events, sizeof(*evt), 0);
    if (!evt)
        return 0;

    __builtin_memset(evt, 0, sizeof(*evt));
    fill_uprobe_event_fields(evt, HG_UPROBE_DIR_READ);

    evt->tls.version = read_tls_version((const void *)ssl);

    int copy_sz = num_read < (int)sizeof(evt->tls.payload_snippet) - 1
                      ? num_read
                      : (int)sizeof(evt->tls.payload_snippet) - 1;

    bpf_probe_read_user(evt->tls.payload_snippet, copy_sz, (const void *)buf);
    evt->tls.payload_snippet[copy_sz] = '\0';

    bpf_ringbuf_submit(evt, 0);
    return 0;
}
