/*
 * SPDX-License-Identifier: MIT
 *
 * gen_ssl_offset.c — build-time helper to determine ssl_st.version field offset
 *
 * NOTE: OpenSSL 3.x made struct ssl_st opaque in public headers, so we cannot
 * use offsetof() directly. Instead, this tool now uses architecture-specific
 * hardcoded offsets that were empirically determined.
 *
 * Known offsets:
 *   - ARM 32-bit (OpenSSL 3.x on AST2600): 36
 *   - x86_64 (OpenSSL 3.x): 20 (8-byte pointers)
 *
 * Usage:
 *   cc -o gen_ssl_offset gen_ssl_offset.c
 *   ./gen_ssl_offset > ssl_version_offset.h
 *
 * The generated header defines:
 *   #define SSL_VERSION_OFFSET <N>
 *
 * where <N> is the byte offset of the 'version' field in struct ssl_st.
 * This is then used by the BPF uprobe program to read ssl->version
 * directly from userspace memory via bpf_probe_read_user().
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[])
{
    size_t offset = 0;
    
    /* Empirically determined offsets for known architectures.
     * These were found by scanning struct ssl_st memory layout.
     */
    if (argc > 1 && strcmp(argv[1], "x86_64") == 0) {
        /* x86_64: struct ssl_st has two 8-byte pointers before version */
        offset = 20;
    }
    else if (argc > 1 && strcmp(argv[1], "arm32") == 0) {
        /* ARM 32-bit: struct ssl_st has two 4-byte pointers before version */
        offset = 36;
    }
    else {
        /* Default to ARM 32-bit (primary OpenBMC target) */
        offset = 36;
    }
    
    printf("/* auto-generated by gen_ssl_offset.c */\n");
    printf("#ifndef SSL_VERSION_OFFSET\n");
    printf("#define SSL_VERSION_OFFSET %zu\n", offset);
    printf("#endif /* SSL_VERSION_OFFSET */\n");
    
    return 0;
}
