# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "httpsguard"
BBFILE_PATTERN_httpsguard = "^${LAYERDIR}/"
BBFILE_PRIORITY_httpsguard = "7"

LAYERSERIES_COMPAT_httpsguard = "kirkstone mickledore nanbield scarthgap styhead"
